version: "3.9"

services:
  aggregator:
    build: ./aggregator
    ports:
      - "8080:8080"
    depends_on:
      - storage
      - broker
    environment:
      - DATABASE_URL=postgres://user:pass@storage:5432/db
      - BROKER_URL=redis://broker:6379
      - ASYNC_MODE=true

  publisher:
    build: ./publisher
    depends_on:
      - aggregator
    environment:
      - TARGET_URL=http://aggregator:8080/publish

  broker:
    image: redis:7-alpine
    ports: [] # tetap internal

  storage:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./storage/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data:
